opts = detectImportOptions('Documents/logs/log_LAPS_CAN_1.csv');
opts.SelectedVariableNames = [2 4];
m = readtable('Documents/logs/log_LAPS_CAN_1.csv',opts);
x1=m{:,1};
y1=m{:,2};
ax1 = subplot(2,1,1);
plot(ax1,x1,y1);
title(ax1,'Distance VS Speed - Lap 1');
ylabel(ax1,'Speed (km/h)');
xlabel(ax1,'Timestamp');
opts = detectImportOptions('Documents/logs/log_LAPS_CAN_2.csv');
opts.SelectedVariableNames = [2 4];
m = readtable('Documents/logs/log_LAPS_CAN_2.csv',opts);
x2=m{:,1};
y2=m{:,2};
ax2 = subplot(2,1,2);
plot(ax2,x2,y2);
title(ax2,'Time VS Speed - Lap 2');
ylabel(ax2,'Speed (km/h)');
xlabel(ax2,'Timestamp');
%ax3 = subplot(3,1,3);
%plot(ax3,x1,y1,x2,y2);
%title(ax3,'Distance VS Speed - Lap 1 vs 2');
%ylabel(ax3,'Speed (km/h)');
%xlabel(ax3,'Distance (m)');