opts = detectImportOptions('Documents/logs/log_LAPS_CAN_2019_05_15_20_08_16.csv');
opts.SelectedVariableNames = [8 9 10];
m = readmatrix('Documents/logs/log_LAPS_CAN_2019_05_15_20_08_16.csv',opts);
m = m(logical(m(:,2)),:);
z=m(:,1);
lat1=m(:,2);
lon1=m(:,3);
stem3(lon1,lat1,z,'Marker','o','MarkerSize',2,'MarkerEdgeColor','blue','MarkerFaceColor','blue','Color','cyan','LineStyle',':','LineWidth',0.1);
grid on;
title('Speed VS Geopoints - Lap 1');
zlabel('Speed (km/h)');
xlabel('Longitudes');
ylabel('Latitudes');